import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import '@/styles/globals.scss';

const font = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={font.className}>{children}</body>
    </html>
  );
}
